# Generated by Django 4.2.7 on 2023-12-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_techlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='technicianlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_id', models.CharField(max_length=32)),
                ('Password', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='techlogin',
        ),
    ]
