# Generated by Django 4.2.7 on 2023-12-22 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_report_detail_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_detail',
            name='report',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.report'),
            preserve_default=False,
        ),
    ]
