# Generated by Django 4.2.5 on 2023-12-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_report_detail_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='technicianlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_id', models.CharField(max_length=32)),
                ('Password', models.CharField(max_length=16)),
            ],
        ),
    ]
