# Generated by Django 4.2.7 on 2023-12-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_report_detail_report'),
    ]

    operations = [
    ]
