# Generated by Django 4.2.7 on 2023-12-22 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20231222_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_detail',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.report'),
        ),
    ]
