# Generated by Django 4.2.7 on 2024-01-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_techadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32)),
                ('Phonenumber', models.ImageField(max_length=10, upload_to='')),
                ('Email', models.EmailField(max_length=254)),
                ('latitude', models.CharField(max_length=128)),
                ('longitude', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=250)),
                ('discription', models.CharField(max_length=600)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
