# Generated by Django 4.2.7 on 2024-01-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_homeservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact', models.IntegerField()),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
