# Generated by Django 4.2.7 on 2024-01-16 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userlogin'),
        ('myapp', '0011_contact'),
    ]

    operations = [
    ]
