# Generated by Django 4.2.7 on 2024-01-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
