# Generated by Django 4.2.7 on 2024-01-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_merge_0006_userlogin_0011_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='adminpage',
        ),
        migrations.DeleteModel(
            name='userlogin',
        ),
        migrations.RemoveField(
            model_name='report',
            name='dispatch_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='investigation',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reference_value',
        ),
        migrations.RemoveField(
            model_name='report',
            name='results',
        ),
        migrations.RemoveField(
            model_name='report',
            name='unit',
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(max_length=50),
        ),
    ]
